#!/usr/bin/env bash
# Configuring Nginx with a custom X-Served-By response header.
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i '/listen \[::\]:80 default_server;/a\        add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
